site_name: Specs-Assistant
markdown_extensions:
  - attr_list
  - md_in_html
plugins:
  - glightbox
theme:
  name: readthedocs
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
